version: 1.0.{build}

branches:
  only:
  - master

# git clone of depth 1
#clone_depth: 1
# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true

configuration: Release

platform: x64

init:
  - dir C:\avvm\node

install:
  - ps: Install-Product node 5.8.0 x64
  - node -v
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install --production --msvs_version=2013
  - npm install -g kthxbai
  - kthxbai
  - curl -LsSO https://nodejs.org/dist/latest/win-x64/node.exe
  - curl -LsSO https://nodejs.org/dist/latest/win-x64/node.lib
  - mkdir letsage
  - move README.md letsage
  - move node_modules letsage
  - move package.json letsage
  - move GO* letsage
  - ren letsage letsage-%APPVEYOR_BUILD_VERSION%
  - 7z a -sfx7z.sfx letsage-win64-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_BRANCH%.exe letsage-%APPVEYOR_BUILD_VERSION% > nul

build: off

test: off

artifacts:
  - path: letsage-win64-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH).exe
    name: letsage-win64

deploy:
  - provider: FTP
    host: ftp.sagecommons.org
    protocol: ftp
    username: upload@sagecommons.org
    password:
      secure: L4I4NkKN7mrQww7GgwPLrA==
    folder: /
    artifact: letsage-win64

